services:
  mongo:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: --logpath /var/log/mongodb/mongod.log

  unitn-rents:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    ports:
      - "9009:9009"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - ollama
    command: ["python", "init.py"]
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - PYTHONUNBUFFERED=1

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./vuetify-frontend
      dockerfile: Dockerfile
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./vuetify-frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - unitn-rents


volumes:
  mongo_data:
  ollama_data:
  node_modules:
